### ISSUE TITLE
Edit/delete buttons in lists

### ISSUE THREAD

**Issue by amnesia7** [neighborland/cache_rocket#5]
How would you go on for adding edit/delete buttons for each item in a collection so that they can be shown alongside the post name (for instance)?

Do you create each link using the Proc syntax and pass them in as keys which seems a little messy or is there a way to pass in post name as a key and pass in an object or an id or something for the edit / delete buttons?

__posts/index.html.erb__
```
<%= render_cached 'post',
  collection: @posts,
  replace: {
    name: -> (post) { post.name },
    ...
%>
```

The kind of output I'm trying to get is (simplified):
```
<tr>
  <td>Post name here</td>
  <td><a href="/posts/1/edit">Edit</a></td>
  <td><a href="/posts/1" data-method="delete">Delete</a></td>
</tr>
```

Thanks

**Comment by teeparham** [comment]
You could make helper methods for the buttons and do it like this:

posts_helper.rb
```ruby
def edit_button(post)
  link_to "edit post", edit_post_path(post)
end

def delete_button(post)
  # delete button code
end
```

_index.html.erb
```erb
<%= render_cached 'post',
          collection: @posts,
          replace: { 
            edit_button: -> (post) { edit_button(post) },
            delete_button: -> (post) { delete_button(post) }
        }
%>
```
_post.html.erb
```erb
<tr>
  <td>Post name here</td>
  <td><%= cache_replace_key :edit_button %></td>
  <td><%= cache_replace_key :delete_button %></td>
</tr>
```

**Comment by amnesia7** [comment]
Thanks @teeparham but is it not possible to mix keys and partials when replacing?
------------------------------

**Comment by teeparham** [comment]
You cannot currently pass a partial as the replace value for each item in a collection. I'm not exactly sure how that would work. You could try something like:

```
<%= render_cached 'post',
          collection: @posts,
          replace: { 
            something: -> (post) { render partial: 'dynamic', post: post }
        }
%>
```

**Comment by amnesia7** [comment]
Yep, that almost worked, but needed to be:
```ruby
<%= render_cached 'post',
          collection: @posts,
          replace: { 
            something: -> (post) { render partial: 'dynamic', locals: { post: post } }
          }
%>
```
Thanks @teeparham

**Comment by amnesia7** [comment]
@teeparham it might also be worth pointing out in the [Use section](https://github.com/neighborland/cache_rocket#use) of the gem's readme that you need to include loading cache_rocket from the lib directory because I don't think autoloading lib files is done by default.
I did this by adding an initializer file called __cache_rocket.rb__ that just contained:
```ruby
require 'cache_rocket'
```
